version: '3.8'

services:
  redis:
    build:
      context: docker/redis

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

  celery-worker:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

  celery-beat:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
