version: '3.8'

volumes:
  django-static:

services:
  backend:
    environment:
      DJANGO_ALLOWED_HOSTS: '*'
      # STATIC_URL: ${STATIC_URL}
    volumes:
      - django-static:/static
    command: ./docker/backend/run.prod.sh

x-aws-cloudformation:
  Resources:
    DbService:
      Properties:
        DeploymentConfiguration:
          MaximumPercent: 100
          MinimumHealthyPercent: 0

    LoadBalancer:
      Properties:
        LoadBalancerAttributes:
          - Key: idle_timeout.timeout_seconds
            Value: '120'

    Backend8000TargetGroup:
      Properties:
        HealthCheckPath: /
        Matcher:
          HttpCode: 200-499
