version: '3.8'

services:
  redis:
    build:
      context: docker/redis
      args:
        - REDIS_PASSWORD

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

  celery-worker:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

  celery-beat:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
