version: '3.8'

services:
  backend:
    environment:
      DEBUG: 'True'

  celery-worker:
    environment:
      DEBUG: 'True'

  celery-beat:
    environment:
      DEBUG: 'True'

x-aws-cloudformation:
  Resources:
    Backend8000Listener:
      Properties:
        Certificates:
          - CertificateArn: 'arn:aws:acm:ap-south-1:135135176603:certificate/6ed2b0e3-7102-4ddf-bb17-ee8a40fb56ca' #replace your deployment certificate from aws certificate manager
        Protocol: HTTPS
